CREATE TABLE public.menu_items (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  section_id text NOT NULL,
  group_title text NOT NULL,
  sort_order integer NOT NULL DEFAULT 0,
  name text NOT NULL,
  description text,
  price text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

GRANT SELECT ON public.menu_items TO anon;
GRANT SELECT ON public.menu_items TO authenticated;
GRANT ALL ON public.menu_items TO service_role;

ALTER TABLE public.menu_items ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Menu is publicly readable"
ON public.menu_items FOR SELECT
TO anon, authenticated
USING (true);

CREATE OR REPLACE FUNCTION public.update_updated_at_column()
RETURNS TRIGGER AS $$ BEGIN NEW.updated_at = now(); RETURN NEW; END; $$
LANGUAGE plpgsql SET search_path = public;

CREATE TRIGGER update_menu_items_updated_at
BEFORE UPDATE ON public.menu_items
FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

CREATE INDEX menu_items_section_idx ON public.menu_items (section_id, sort_order);

INSERT INTO public.menu_items (section_id, group_title, sort_order, name, description, price) VALUES
('petit-dejeuner', 'Formules', 0, 'Starter', 'Café, croissant, eau 0.5L & mini jus', '12'),
('petit-dejeuner', 'Formules', 1, 'Sweet Mountain', 'Café, eau 0.5L, croissant ou gâteau, confiture, miel, chocolat, pancake ou crêpe, jus, fondant, pain', '22'),
('petit-dejeuner', 'Formules', 2, 'Everest — 1 pers.', 'Café, pâte à tartiner, poulet croustillant et sa sauce, batbout harissa-thon, fondant, confiture, pommes de terre crémeuses, croissant, pancake, omelette, charcuterie & fruits de saison', '32'),
('petit-dejeuner', 'Formules', 3, 'Everest — 2 pers.', NULL, '49'),
('petit-dejeuner', 'Formules', 4, 'Everest — 3 pers.', NULL, '69'),
('petit-dejeuner', 'Formules', 5, 'Kids', 'Pancake ou crêpe, salade de fruits, œuf, yaourt, eau 0.5L, grain d''or & lait au chocolat', '15'),
('cafes', 'Cafés', 0, 'Espresso', NULL, '4'),
('cafes', 'Cafés', 1, 'Américano', NULL, '4,5'),
('cafes', 'Cafés', 2, 'Cappucin', NULL, '4,5'),
('cafes', 'Cafés', 3, 'Lait chocolaté', NULL, '5'),
('cafes', 'Cafés', 4, 'Café latte', NULL, '5'),
('cafes', 'Cafés', 5, 'Cappuccino', NULL, '6'),
('cafes', 'Cafés', 6, 'Macchiato caramel', NULL, '6'),
('cafes', 'Cafés', 7, 'Macchiato noisette', NULL, '6'),
('cafes', 'Cafés', 8, 'Café glacé', NULL, '7'),
('cafes', 'Cafés', 9, 'Affogato', NULL, '8'),
('cafes', 'Chocolat Chaud', 1000, 'Classique', NULL, '8'),
('cafes', 'Chocolat Chaud', 1001, 'Nutella', NULL, '10'),
('cafes', 'Chocolat Chaud', 1002, 'Snickers', NULL, '10'),
('cafes', 'Chocolat Chaud', 1003, 'Kinder', NULL, '10'),
('cafes', 'Thé', 2000, 'Classique', NULL, '3,5'),
('cafes', 'Thé', 2001, 'Sirop', NULL, '4,5'),
('cafes', 'Thé', 2002, 'Amande', NULL, '7'),
('cafes', 'Thé', 2003, 'Pignons', NULL, '9'),
('cafes', 'Frappuccino', 3000, 'Caramel', NULL, '10'),
('cafes', 'Frappuccino', 3001, 'Noisette', NULL, '10'),
('cafes', 'Frappuccino', 3002, 'Vanille', NULL, '10'),
('cafes', 'Frappuccino', 3003, 'Oreo', NULL, '11'),
('cafes', 'Frappuccino', 3004, 'Nutella', NULL, '11'),
('cafes', 'Frappuccino', 3005, 'Speculoos', NULL, '13'),
('fraicheur', 'Mojito', 0, 'Virgin', NULL, '9'),
('fraicheur', 'Mojito', 1, 'Blue', NULL, '10'),
('fraicheur', 'Mojito', 2, 'Red', NULL, '10'),
('fraicheur', 'Mojito', 3, 'Pêche', NULL, '11'),
('fraicheur', 'Mojito', 4, 'Kiwi', NULL, '11'),
('fraicheur', 'Mojito', 5, 'Fraise', NULL, '11'),
('fraicheur', 'Mojito', 6, 'Énergétique', NULL, '14'),
('fraicheur', 'Jus', 1000, 'Orange', NULL, '7'),
('fraicheur', 'Jus', 1001, 'Citronnade', NULL, '8'),
('fraicheur', 'Jus', 1002, 'Fraise', NULL, '8'),
('fraicheur', 'Jus', 1003, 'Cocktail', NULL, '10'),
('fraicheur', 'Jus', 1004, 'Piña Colada', NULL, '11'),
('fraicheur', 'Jus', 1005, 'Cocktail énergétique', NULL, '13'),
('fraicheur', 'Smoothie', 2000, 'Fraise banane', NULL, '12'),
('fraicheur', 'Smoothie', 2001, 'Acajou banane', NULL, '12'),
('fraicheur', 'Smoothie', 2002, 'Kiwi banane', NULL, '12'),
('fraicheur', 'Smoothie', 2003, 'Fruits rouges banane', NULL, '13'),
('fraicheur', 'Smoothie', 2004, 'Blue berry', NULL, '13'),
('fraicheur', 'Smoothie', 2005, 'Avocat banane', NULL, '14'),
('fraicheur', 'Detox', 3000, 'Gingembre citron ananas', NULL, '10'),
('fraicheur', 'Detox', 3001, 'Kiwi banane orange', NULL, '10'),
('fraicheur', 'Detox', 3002, 'Gingembre mangue', NULL, '10'),
('fraicheur', 'Milkshake', 4000, 'Caramel', NULL, '10'),
('fraicheur', 'Milkshake', 4001, 'Oreo', NULL, '11'),
('fraicheur', 'Milkshake', 4002, 'Nutella', NULL, '12'),
('fraicheur', 'Milkshake', 4003, 'Kinder', NULL, '12'),
('fraicheur', 'Milkshake', 4004, 'Snickers', NULL, '12'),
('fraicheur', 'Milkshake', 4005, 'Sweet blood', NULL, '13'),
('fraicheur', 'Milkshake', 4006, 'Oreo Nutella', NULL, '14'),
('fraicheur', 'Saveurs Liquides', 5000, 'Eau minérale 0.5L', NULL, '2,5'),
('fraicheur', 'Saveurs Liquides', 5001, 'Eau minérale 1L', NULL, '3,5'),
('fraicheur', 'Saveurs Liquides', 5002, 'Soda', NULL, '4,5'),
('fraicheur', 'Saveurs Liquides', 5003, 'Eau gazeuse', NULL, '5'),
('fraicheur', 'Saveurs Liquides', 5004, 'Boisson énergétique', NULL, '10'),
('sucre', 'Crêpe Sucrée', 0, 'Nutella', NULL, '13'),
('sucre', 'Crêpe Sucrée', 1, 'Ottelo', NULL, '14'),
('sucre', 'Crêpe Sucrée', 2, 'Snickers', NULL, '14'),
('sucre', 'Crêpe Sucrée', 3, 'Kinder', NULL, '15'),
('sucre', 'Crêpe Sucrée', 4, 'Rocher', NULL, '15'),
('sucre', 'Crêpe Sucrée', 5, 'Nutella & fruits secs', NULL, '15'),
('sucre', 'Crêpe Sucrée', 6, 'Nutella & banane', NULL, '16'),
('sucre', 'Crêpe Sucrée', 7, 'Pistache', NULL, '16'),
('sucre', 'Pancake', 1000, 'Nutella', NULL, '13'),
('sucre', 'Pancake', 1001, 'Ottelo', NULL, '14'),
('sucre', 'Pancake', 1002, 'Snickers', NULL, '14'),
('sucre', 'Pancake', 1003, 'Kinder', NULL, '15'),
('sucre', 'Pancake', 1004, 'Rocher', NULL, '15'),
('sucre', 'Pancake', 1005, 'Nutella & fruits secs', NULL, '15'),
('sucre', 'Pancake', 1006, 'Nutella & banane', NULL, '16'),
('sucre', 'Pancake', 1007, 'Pistache', NULL, '16'),
('sucre', 'Pâtisseries', 2000, 'Croissant', NULL, '3,5'),
('sucre', 'Pâtisseries', 2001, 'Cake', NULL, '4'),
('sucre', 'Pâtisseries', 2002, 'Tarte', NULL, '5'),
('sucre', 'Pâtisseries', 2003, 'Gâteaux', NULL, '7'),
('sucre', 'Pâtisseries', 2004, 'Fondant au chocolat', NULL, '8'),
('sucre', 'Pâtisseries', 2005, 'Glace', NULL, '9'),
('sucre', 'Pâtisseries', 2006, 'Cheesecake', NULL, '13'),
('sucre', 'Suppléments', 3000, 'Sirop', NULL, '1'),
('sucre', 'Suppléments', 3001, 'Crème chantilly', NULL, '2'),
('sucre', 'Suppléments', 3002, 'Fruits secs', NULL, '4'),
('sucre', 'Suppléments', 3003, 'Fruits frais', NULL, '4'),
('sucre', 'Suppléments', 3004, 'Frites', NULL, '4'),
('sale', 'Pizza', 0, 'Margherita', NULL, '12'),
('sale', 'Pizza', 1, 'Végétarienne', NULL, '12'),
('sale', 'Pizza', 2, 'Jambon', NULL, '14'),
('sale', 'Pizza', 3, 'Neptune', NULL, '15'),
('sale', 'Pizza', 4, 'Escalope', NULL, '17'),
('sale', 'Pizza', 5, '4 saisons', NULL, '18'),
('sale', 'Pizza', 6, '4 fromages', NULL, '20'),
('sale', 'Baguette Farcie', 1000, 'Thon', NULL, '12'),
('sale', 'Baguette Farcie', 1001, 'Escalope', NULL, '15'),
('sale', 'Baguette Farcie', 1002, 'Escalope croustillante', NULL, '16'),
('sale', 'Makloub', 2000, 'Thon', NULL, '12'),
('sale', 'Makloub', 2001, 'Escalope', NULL, '14'),
('sale', 'Makloub', 2002, 'Escalope croustillante', NULL, '15'),
('sale', 'Crêpe Salée', 3000, 'Classique', NULL, '12'),
('sale', 'Crêpe Salée', 3001, 'Française', NULL, '13'),
('sale', 'Crêpe Salée', 3002, 'Tunisienne', NULL, '13'),
('sale', 'Crêpe Salée', 3003, 'Fromage', NULL, '14'),
('sale', 'Crêpe Salée', 3004, 'Escalope', NULL, '15'),
('sale', 'Omelette', 4000, 'Fromage', NULL, '8'),
('sale', 'Omelette', 4001, 'Thon', NULL, '10'),
('sale', 'Omelette', 4002, 'Jambon', NULL, '10'),
('sale', 'Omelette', 4003, 'Escalope', NULL, '13'),
('sale', 'Chicha', 5000, 'Turc', NULL, '13'),
('sale', 'Chicha', 5001, 'Kaloud', NULL, '15');